version: '3.5'

services:

  mysql-db:
    # image: mysql:8.0
    build:
      context: ./sql
    restart: always  
    container_name: mysql-db
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_HOST=127.0.0.1
    ports:
      - '7010:3306'
    expose:
      - '7010'
    networks:
      - proxy

  lumen:
    build:
      context: '.'
    container_name: lumen
    restart: always
    labels:
      - traefik.enable=true
      # HTTP router with redirect
      - traefik.http.routers.lumen-http.entrypoints=web
      - traefik.http.routers.lumen-http.rule=Host(`lumen.sketapp.com`)
      - traefik.http.routers.lumen-http.middlewares=lumen-redirect-to-https
      # HTTPS
      - traefik.http.routers.lumen-https.entrypoints=web-secured
      - traefik.http.routers.lumen-https.rule=Host(`lumen.sketapp.com`)
      - traefik.http.routers.lumen-https.tls=true
      - traefik.http.routers.lumen-https.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.lumen-redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.lumen-redirect-to-https.redirectscheme.permanent=true
      
    volumes:
      - .:/var/www/html
    ports:
     - 8085:80
    networks:
     - proxy

networks:
  proxy:
    external: true
volumes:
  my-db: {}